trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
 - checkout: self
   submodules: true
 - task: VSBuild@1
   inputs:
     solution: ShaderCompile.sln
     configuration: Release
     platform: x64
 - task: CopyFiles@2
   inputs:
     SourceFolder: 'x64\Release'
     Contents: '*.exe'
     TargetFolder: $(Build.ArtifactStagingDirectory)
 - task: CopyFiles@2
   inputs:
     SourceFolder: 'scripts'
     Contents: '**'
     TargetFolder: $(Build.ArtifactStagingDirectory)
 - task: PublishPipelineArtifact@1
   inputs:
     targetPath: $(Build.ArtifactStagingDirectory)